import { NextResponse } from 'next/server';
import puppeteer from 'puppeteer';

export async function POST(req: Request) {
  try {
    const { stats, filters, profile, date } = await req.json();

    // 1. Launch Browser
    const browser = await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    const page = await browser.newPage();

    // 2. Build HTML Content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: sans-serif; padding: 40px; color: #333; }
          h1 { color: #1e293b; margin-bottom: 5px; }
          .meta { color: #64748b; margin-bottom: 30px; font-size: 0.9em; }
          .card-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
          .summary-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 30px; }
          .card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; background: #fff; }
          .card h3 { margin: 0 0 10px 0; font-size: 0.9em; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
          .card .value { font-size: 1.8em; font-weight: bold; color: #0f172a; }
          .section-title { font-size: 1.2em; font-weight: bold; margin-bottom: 15px; border-bottom: 1px solid #e2e8f0; padding-bottom: 10px; margin-top: 30px; }
          .row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f1f5f9; }
          .row:last-child { border-bottom: none; }
          .row span:last-child { font-weight: 600; }
          .footer { margin-top: 50px; text-align: center; font-size: 0.8em; color: #94a3b8; }
        </style>
      </head>
      <body>
        <h1>Sales Report</h1>
        <div class="meta">
          Generated on: ${date}<br/>
          Generated by: ${profile?.full_name || 'System'}<br/>
          ${filters.startDate ? `Period: ${filters.startDate} to ${filters.endDate}` : 'Period: All Time'}
        </div>

        <div class="summary-grid" style="grid-template-columns: 1fr 1fr;">
          <div class="card">
            <h3>Total Leads</h3>
            <div class="value">${stats.totalLeads}</div>
          </div>
          <div class="card">
            <h3>Total Accounts</h3>
            <div class="value">${stats.totalAccounts}</div>
          </div>
        </div>

        <div class="card-grid">
          <div class="card">
            <h3>Leads by Status</h3>
            ${Object.entries(stats.leadsByStatus).map(([k, v]) => `
              <div class="row"><span>${k}</span><span>${v}</span></div>
            `).join('')}
          </div>
          <div class="card">
            <h3>Accounts by Stage</h3>
            ${Object.entries(stats.accountsByStage).map(([k, v]) => `
              <div class="row"><span>${k}</span><span>${v}</span></div>
            `).join('')}
          </div>
        </div>

        <div class="footer">
          Confidential - CRM System Report
        </div>
      </body>
      </html>
    `;

    await page.setContent(htmlContent);

    // 3. Generate PDF
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' },
    });

    await browser.close();

    // 4. Return Response
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="report-${Date.now()}.pdf"`,
      },
    });

  } catch (error: any) {
    console.error('PDF Generation Error:', error);
    return NextResponse.json({ error: 'Failed to generate PDF: ' + error.message }, { status: 500 });
  }
}
